### ISSUE TITLE
Inefficient searching algorithm

### ISSUE THREAD

**Issue by SOF3** [Bluzzi/ChestFinder#1]
The plugin searches all tiles in a level, which may lag the server if there are lots of them. Consider indexing the tiles.

**Comment by Bluzzi** [comment]
This solution is more optimized [commit container-tiles](https://github.com/Bluzzi/ChestFinder/commit/d1b25097cd22e49484587a8b27e40b95d00c1250) ?

Or I can do another system that looks for the tiles in all chunks in the radius indicated in the config not all tiles in a level ? (with a max radius).

**Comment by SOF3** [comment]
Best if you implement an R-tree (or at least a B-tree) to search.

**Comment by Bluzzi** [comment]
This is perfect [commit container-tiles - add R-tree search system](https://github.com/Bluzzi/ChestFinder/commit/fb4e11c8ff646d2ff62bedee6a525696498de574) ?

**Comment by SOF3** [comment]
That's not exactly an R-tree, but looks satisfactory for the purpose

**Comment by Bluzzi** [comment]
Mm... okay, I’ll try to learn a little more about the R-Tree when I have time ! And I would make a better version !

In the meantime, I’m sending this version to Poggit :no_mouth:

Thank you for your help ! And sorry for my bad English :sweat:

**Comment by SOF3** [comment]
I believe R-tree isn't strictly necessary here, because you can't have too many chests within the radius anyway.
