### ISSUE TITLE
Update to PocketMine 4.0.0+

### ISSUE THREAD

**Issue by ByLex-69bits** [Bluzzi/ChestFinder#12]
Update to PocketMine 4.0.0+

**Comment by Bluzzi** [comment]
Hello, I don't work on PocketMine at all anymore so I won't update this plugin to PM4. 

However, I'm still available to manage pull requests from this repo. So if someone wants to open a pull request for the upgrade of this plugin to PM4, I'll participate in the verification/publication of the code.

**Comment by Steellgold** [comment]
Hey @Bluzzi, i submitted a Pull Request https://github.com/Symphonia-Team/ChestFinder/pull/13 for update to PM4

**Comment by Bluzzi** [comment]
Its done ! @ByLex-69bits
