### ISSUE TITLE
Idea for new...

### ISSUE THREAD

**Issue by zerko43** [Bluzzi/ChestFinder#4]
Hello, an addition that would be cool:

Be able to choose the distance before indicating the exact distance with the chest.

Example (+20 blocks with the chest):
"§aThere are {chestCount} chest(s) near you..."

Example (-20 blocks with the chest):
"§aThere are {chestCount} chest(s) near you...{lineBreak}The closest chest near you is at {chestDistance} blocks !"

**Comment by Bluzzi** [comment]
Sorry this plugin will not be updated by me anymore, you can open a pull request if you want to add this feature.

**Comment by Steellgold** [comment]
Can you be a little more detailed?

**Comment by Steellgold** [comment]
@Bluzzi I think you can close this issue definitely
