### ISSUE TITLE
nice idea

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Bluzzi/ChestFinder#7]
Can i use it to find, for example diamonds?

**Comment by TDMidkwhatisxd** [comment]
But i use basichud, wont interfere with plugin?

**Comment by Bluzzi** [comment]
I have added possibility to [send tip or title instead popup](https://github.com/Bluzzi/ChestFinder/commit/8becff6ebb01e901321f281f9a8073c0674c8c14), you can use this to avoid conflict with BasicHUD.

This plugin is not used to search for diamond or another block, sorry.
